[theme]
base = "dark"
primaryColor = "#e8629a"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e1e2e"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
